apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ky4yx5wzo-dotnet-basic
  janus-idp.io/tekton: ky4yx5wzo-dotnet-basic
  backstage.io/kubernetes-id: ky4yx5wzo-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ky4yx5wzo-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
